# import { gql, useQuery } from '@apollo/client'

# const GetPreferences = gql`
query GetPreferences ($owner: Int, $last: Int, $after: String, $before: String) {
  preferencess (first: $owner, last: $last, after: $after, before: $before) {
    nodes {
      preferencesId
      title
      content
      status
      link
      modified
      # custom fields
      doAutoLoadData
      doAutoRotate
      preferencesId
      projectName
      version
      # owner
    }
  }
  # files {
  #   nodes
  # }
}
# `
