query GetProjects {
  projects {
    nodes {
      projectId
      title
      content
      link
      version
      modified
      preferences {
        node {
          preferencesId
          title
          content
          link
          modified
          # custom fields
          projectName
          doAutoLoadData
          doAutoRotate
          # owner
          version
        }
      }
      scenes {
        nodes {
          sceneId
          title
          content
          link
          version
          modified
          # custom fields
          sceneBgColor
          sceneBgImage {
            node {
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
          }
          scenePlaneWidthX
          scenePlaneHeightY
          scenePlaneLengthZ
          scenePlaneTextureRepeatX
          scenePlaneTextureRepeatY
          scenePlaneTextureRepeatZ
          sceneBgImagePz {
            node {
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
          }
          sceneBgImagePy {
            node {
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
          }
          sceneBgImagePx {
            node {
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
          }
          sceneBgImageNz {
            node {
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
          }
          sceneBgImageNy {
            node {
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
          }
          sceneBgImageNx {
            node {
              sourceUrl
              link
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
          }
        }
      }
      plans {
        nodes {
          planId
          title
          content
          link
          version
          modified
          # custom fields
          threeds {
            nodes {
              threedId
              title
              # content
              # link
              # version
              # modified
              # # custom fields
              # positionX
              # positionY
              # positionZ
              # rotationX
              # rotationY
              # rotationZ
              # scaleX
              # scaleY
              # scaleZ
              # # children
              # files {
              #   nodes {
              #     fileId
              #     title
              #     fileType
              #     isObject3d
              #     isUrl
              #     url
              #     link
              #     modified
              #     file {
              #       node {
              #         title
              #         sourceUrl
              #         mediaItemId
              #         mediaItemUrl
              #         mediaType
              #         link
              #       }
              #     }
              #   }
              # }
            }
          }
          threedsActive {
            nodes {
              threedId
              title
              content
              link
              version
              modified
              # custom fields
              positionX
              positionY
              positionZ
              rotationX
              rotationY
              rotationZ
              scaleX
              scaleY
              scaleZ
              # children
              files {
                nodes {
                  fileId
                  title
                  fileType
                  isObject3d
                  isUrl
                  url
                  link
                  modified
                  file {
                    node {
                      title
                      sourceUrl
                      mediaItemId
                      mediaItemUrl
                      mediaType
                      link
                    }
                  }
                }
              }
            }
          }
          threedsInactive {
            nodes {
              threedId
              title
              # content
              # link
              # version
              # modified
              # # custom fields
              # positionX
              # positionY
              # positionZ
              # rotationX
              # rotationY
              # rotationZ
              # scaleX
              # scaleY
              # scaleZ
              # # children
              # files {
              #   nodes {
              #     fileId
              #     title
              #     fileType
              #     isObject3d
              #     isUrl
              #     url
              #     link
              #     modified
              #     file {
              #       node {
              #         title
              #         sourceUrl
              #         mediaItemId
              #         mediaItemUrl
              #         mediaType
              #         link
              #       }
              #     }
              #   }
              # }
            }
          }
          # custom fields (from v2 demo)
          # _id: newUUID(),
          # _ts: new Date().toISOString(),
          # levels: [{ id: 0, height: 0 }] as Object[],
          # // levels[0]: { id: 0, height: 0 },
          # floors: [] as Object[],
          # roofs: [] as Object[],
          # walls: [] as Object[],
          # dimensions: [] as Object[],
          # texts: [] as Object[],
          # furniture: [] as Object[],

          # verticalGuides: [] as Object[],
          # horizontalGuides: [] as Object[],

          # furnitureAddedKey: null as any,
          # furnitureDirtyKey: null as any,
          # furnitureDeletedKey: null as any,
          # wallAddedKey: null as any,
          # wallDirtyKey: null as any,
          # wallDeletedKey: null as any,
          # roofAddedKey: null as any,
          # roofDirtyKey: null as any,
          # roofDeletedKey: null as any,
          # floorAddedKey: null as any,
          # floorDirtyKey: null as any,
          # floorDeletedKey: null as any,
          # dimensionAddedKey: null as any,
          # dimensionEditedKey: null as any,
          # dimensionDeletedKey: null as any,
          # textAddedKey: null as any,
          # textEditedKey: null as any,
          # textDeletedKey: null as any,

          # // wallDiffuse: wallMaterial.color.getHexString(),
          # // wallOpacity: wallMaterial.opacity,
          # // wallSpecular: wallMaterial.specular.getHexString(),
          # // roofDiffuse: roofMaterial.color.getHexString(),
          # // roofOpacity: roofMaterial.opacity,
          # // roofSpecular: roofMaterial.specular.getHexString(),
          # // floorDiffuse: floorMaterial.color.getHexString(),
          # // floorOpacity: floorMaterial.opacity,
          # // floorSpecular: floorMaterial.specular.getHexString(),
          # // groundDiffuse: groundMaterial.color.getHexString(),
          # // groundOpacity: groundMaterial.opacity,
          # // groundSpecular: groundMaterial.specular.getHexString(),

          # depthWrite: 'checked', // document.getElementById("depthWriteMode").checked,
          # sortObjects: 'checked', // document.getElementById("sortObjectsMode").checked,

          # // azimuth: azimuth,
          # // inclination: inclination
        }
      }
    }
  }
}
