query GetProjects {
  projects {
    nodes {
      projectId
      title
      content
      uri
      version
      modified
      # template {
      #   templateName
      # }
      settings {
        nodes {
          # settingsId
          # THREED SETTINGS
          doAutoLoadData
          doAutoRotate
          projectName
          # owner
          version
          # from wp built-in (THREED + WP)
          # discussionSettingsDefaultPingStatus
          # discussionSettingsDefaultCommentStatus
          # generalSettingsDateFormat
          # generalSettingsDescription
          # generalSettingsEmail
          # generalSettingsLanguage
          # generalSettingsStartOfWeek
          # generalSettingsTimeFormat
          # generalSettingsTimezone
          # generalSettingsTitle
          # generalSettingsUrl
          # readingSettingsPageForPosts
          # readingSettingsPageOnFront
          # readingSettingsPostsPerPage
          # readingSettingsShowOnFront
          # writingSettingsDefaultCategory
          # writingSettingsDefaultPostFormat
          # writingSettingsUseSmilies
        }
      }
      scenes {
        nodes {
          sceneId
          title
          content
          uri
          version
          modified
          # template {
          #   templateName
          # }
          sceneBgColor
          sceneBgImage {
            node {
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
            # cursor
          }
          scenePlaneWidthX
          scenePlaneHeightY
          scenePlaneLengthZ
          scenePlaneTextureRepeatX
          scenePlaneTextureRepeatY
          scenePlaneTextureRepeatZ
          sceneBgImagePz {
            node {
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
            # cursor
          }
          sceneBgImagePy {
            node {
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
            # cursor
          }
          sceneBgImagePx {
            node {
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
            # cursor
          }
          sceneBgImageNz {
            node {
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
            # cursor
          }
          sceneBgImageNy {
            node {
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
            # cursor
          }
          sceneBgImageNx {
            node {
              sourceUrl
              uri
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
            # cursor
          }
        }
      }
      plans {
        nodes {
          planId
          title
          content
          uri
          version
          modified
          # template {
          #   templateName
          # }
          threeds {
            nodes {
              threedId
              title
              # content
              # uri
              # version
              # modified
              # # custom fields
              # positionX
              # positionY
              # positionZ
              # rotationX
              # rotationY
              # rotationZ
              # scaleX
              # scaleY
              # scaleZ
              # # template {
              # #   templateName
              # # }
              # # children
              # files {
              #   nodes {
              #     fileId
              #     title
              #     fileType
              #     isObject3d
              #     isUrl
              #     url
              #     uri
              #     modified
              #     file {
              #       node {
              #         title
              #         sourceUrl
              #         mediaItemId
              #         mediaItemUrl
              #         mediaType
              #         uri
              #       }
              #     }
              #   }
              # }
            }
          }
          threedsActive {
            nodes {
              threedId
              title
              content
              uri
              version
              modified
              # custom fields
              positionX
              positionY
              positionZ
              rotationX
              rotationY
              rotationZ
              scaleX
              scaleY
              scaleZ
              # template {
              #   templateName
              # }
              # children
              files {
                nodes {
                  fileId
                  title
                  fileType
                  isObject3d
                  isUrl
                  url
                  uri
                  modified
                  file {
                    node {
                      title
                      sourceUrl
                      mediaItemId
                      mediaItemUrl
                      mediaType
                      uri
                    }
                  }
                }
              }
            }
          }
          threedsInactive {
            nodes {
              threedId
              title
              # content
              # uri
              # version
              # modified
              # # custom fields
              # positionX
              # positionY
              # positionZ
              # rotationX
              # rotationY
              # rotationZ
              # scaleX
              # scaleY
              # scaleZ
              # # template {
              # #   templateName
              # # }
              # # children
              # files {
              #   nodes {
              #     fileId
              #     title
              #     fileType
              #     isObject3d
              #     isUrl
              #     url
              #     uri
              #     modified
              #     file {
              #       node {
              #         title
              #         sourceUrl
              #         mediaItemId
              #         mediaItemUrl
              #         mediaType
              #         uri
              #       }
              #     }
              #   }
              # }
            }
          }
        }
      }
    }
  }
}
