query GetProjects {
  projects {
    nodes {
      projectId
      title
      content
      link
      version
      modified
      preferences {
        node {
          preferencesId
          title
          content
          link
          modified
          # custom fields
          doAutoLoadData
          doAutoRotate
          projectName
          # owner
          version
        }
      }
      scenes {
        nodes {
          sceneId
          title
          content
          link
          version
          modified
          # custom fields
          sceneBgColor
          sceneBgImage {
            node {
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
          }
          scenePlaneWidthX
          scenePlaneHeightY
          scenePlaneLengthZ
          scenePlaneTextureRepeatX
          scenePlaneTextureRepeatY
          scenePlaneTextureRepeatZ
          sceneBgImagePz {
            node {
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
          }
          sceneBgImagePy {
            node {
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
          }
          sceneBgImagePx {
            node {
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
          }
          sceneBgImageNz {
            node {
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
          }
          sceneBgImageNy {
            node {
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
          }
          sceneBgImageNx {
            node {
              sourceUrl
              link
              title
              mediaType
              mediaItemUrl
              mediaItemId
              mediaDetails {
                file
              }
            }
          }
        }
      }
      plans {
        nodes {
          planId
          title
          content
          link
          version
          modified
          # custom fields
          threeds {
            nodes {
              threedId
              title
              # content
              # link
              # version
              # modified
              # # custom fields
              # positionX
              # positionY
              # positionZ
              # rotationX
              # rotationY
              # rotationZ
              # scaleX
              # scaleY
              # scaleZ
              # # children
              # files {
              #   nodes {
              #     fileId
              #     title
              #     fileType
              #     isObject3d
              #     isUrl
              #     url
              #     link
              #     modified
              #     file {
              #       node {
              #         title
              #         sourceUrl
              #         mediaItemId
              #         mediaItemUrl
              #         mediaType
              #         link
              #       }
              #     }
              #   }
              # }
            }
          }
          threedsActive {
            nodes {
              threedId
              title
              content
              link
              version
              modified
              # custom fields
              positionX
              positionY
              positionZ
              rotationX
              rotationY
              rotationZ
              scaleX
              scaleY
              scaleZ
              # children
              files {
                nodes {
                  fileId
                  title
                  fileType
                  isObject3d
                  isUrl
                  url
                  link
                  modified
                  file {
                    node {
                      title
                      sourceUrl
                      mediaItemId
                      mediaItemUrl
                      mediaType
                      link
                    }
                  }
                }
              }
            }
          }
          threedsInactive {
            nodes {
              threedId
              title
              # content
              # link
              # version
              # modified
              # # custom fields
              # positionX
              # positionY
              # positionZ
              # rotationX
              # rotationY
              # rotationZ
              # scaleX
              # scaleY
              # scaleZ
              # # children
              # files {
              #   nodes {
              #     fileId
              #     title
              #     fileType
              #     isObject3d
              #     isUrl
              #     url
              #     link
              #     modified
              #     file {
              #       node {
              #         title
              #         sourceUrl
              #         mediaItemId
              #         mediaItemUrl
              #         mediaType
              #         link
              #       }
              #     }
              #   }
              # }
            }
          }
        }
      }
    }
  }
}
