import { strict as assert } from 'node:assert';
import { modelForPreview, resolvePreviewRequirements } from '../../components/admin/threed/models/model-preview-requirements';
const texture = { fileName: 'PolygonFarm_Texture_01_A.png', filePath: 'https://test/texture.png', isActive: true };
const model = { id: 11, modelName: 'Character', modelType: 'fbx', filePath: 'https://test/model.fbx', files: [], textureFallbacks: [texture] };
const requirements = [{ kind: 'texture', relativePath: 'Textures/PolygonFarm_Texture_01_A.png', satisfied: false }, { kind: 'buffer', relativePath: 'mesh.bin', satisfied: false }];
assert.equal(resolvePreviewRequirements(model, requirements)[0].satisfied, false, 'Owner library match is not a saved dependency');
assert.deepEqual(modelForPreview(model).textureFallbacks, []);
assert.equal(modelForPreview(model).renderingAssetsResolved, true, 'Prevent implicit owner API fallback');
assert.deepEqual(modelForPreview(model, true).textureFallbacks, [texture]);
const assigned = { ...model, materialAssignments: [{ targetKey: '*', channel: 'baseColor', textureId: 1, textureName: 'Atlas', textureFileName: texture.fileName, textureUrl: texture.filePath }] };
assert.equal(resolvePreviewRequirements(assigned, requirements)[0].satisfied, true);
assert.equal(resolvePreviewRequirements(assigned, requirements)[1].satisfied, false);
const attached = { ...model, files: [{ ...texture, relativePath: requirements[0].relativePath, fileType: 'texture' }] };
assert.equal(resolvePreviewRequirements(attached, requirements)[0].satisfied, true);
assert.equal(model.textureFallbacks.length, 1, 'Do not mutate source model');
console.log('PASS saved-only preview, explicit owner troubleshooting, saved attachment/material resolution');
