import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import assert from 'node:assert/strict';
import { PhysicsSensorCuboidsEditor } from '../../components/map/details/PhysicsSensorCuboidsEditor';
import { SceneTransformWorkspace } from '../../components/threed/transform/SceneTransformWorkspace';
(globalThis as any).React = React;
const sensor = (id:string,name:string) => ({id,name,behavior:'counter',detection:'movable-ball',groupId:null,position:{x:0,y:1,z:0},width:2,height:2,depth:.35,rotationY:0});
const props = {markerId:1,ownerKey:'15:models:1',ownerPose:{position:{x:0,y:0,z:0},rotation:[0,0,0]},initialMetadata:{physicsSensorCuboids:[sensor('a','Entrance A'),sensor('b','Entrance B')]},saving:false,placementSensorId:null,placementResult:null,onBeginPlacement:()=>{},onCancelPlacement:()=>{},onZoomToSensor:()=>{},onSave:async()=>true,onSelectSensor:()=>{}};
const render = (id:string|null) => renderToStaticMarkup(React.createElement(SceneTransformWorkspace,null,React.createElement(PhysicsSensorCuboidsEditor,{...props,selectedSensorId:id} as any)));
const parent=render(null);
assert(parent.includes('Entrance A') && parent.includes('Entrance B'));
assert(!parent.includes('type="number"'));
const first=render('a');
assert(first.includes('value="Entrance A"') && !first.includes('Entrance B'));
assert(first.includes('Move Sensor') && first.includes('Zoom to Sensor') && first.includes('Transform Sensor'));
assert.equal((first.match(/type="number"/g)||[]).length,7);
const second=render('b');
assert(second.includes('value="Entrance B"') && !second.includes('Entrance A'));
assert(first.indexOf('Save Sensor')<first.indexOf('value="Entrance A"'));
console.log('PASS: parent lists both sensors without forms; each sensor inspector renders only its own seven transform fields and actions.');
