import mock from './mock'
import './cards'
import './table'
import './auth/jwt'
// import './modules/chat'
import './pages/faq'
// import './modules/email'
// import './modules/invoice'
import './autocomplete'
// import './modules/user'
// import './modules/calendar'
import './pages/pricing'
import './app-bar-search'
// import './modules/permissions'
import './pages/knowledge-base'
import './server-side-menu/vertical'
import './server-side-menu/horizontal'

mock.onAny().passThrough()
