import mock from './mock'
import './auth/jwt'
import './modules/calendar'
import './modules/chat'
import './modules/email'
import './modules/invoice'
import './modules/permissions'
import './modules/userList'
import './app-bar-search'
import './autocomplete'
import './cards'
import './table'
import './pages/faq'
import './pages/pricing'
import './pages/knowledge-base'
import './server-side-menu/vertical'
import './server-side-menu/horizontal'

mock.onAny().passThrough()
