/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mesh0_mesh: THREE.Mesh
    mesh0_mesh_1: THREE.Mesh
    mesh0_mesh_2: THREE.Mesh
    mesh0_mesh_3: THREE.Mesh
    mesh0_mesh_4: THREE.Mesh
    mesh0_mesh_5: THREE.Mesh
    mesh0_mesh_6: THREE.Mesh
    mesh0_mesh_7: THREE.Mesh
    mesh0_mesh_8: THREE.Mesh
    mesh0_mesh_9: THREE.Mesh
    mesh0_mesh_10: THREE.Mesh
    mesh0_mesh_11: THREE.Mesh
    mesh0_mesh_12: THREE.Mesh
    mesh0_mesh_13: THREE.Mesh
    mesh0_mesh_14: THREE.Mesh
    mesh0_mesh_15: THREE.Mesh
    mesh0_mesh_16: THREE.Mesh
    mesh0_mesh_17: THREE.Mesh
    mesh0_mesh_18: THREE.Mesh
    mesh0_mesh_19: THREE.Mesh
    mesh0_mesh_20: THREE.Mesh
    mesh0_mesh_21: THREE.Mesh
    mesh0_mesh_22: THREE.Mesh
    mesh0_mesh_23: THREE.Mesh
    mesh0_mesh_24: THREE.Mesh
    mesh0_mesh_25: THREE.Mesh
    mesh0_mesh_26: THREE.Mesh
    mesh0_mesh_27: THREE.Mesh
    mesh0_mesh_28: THREE.Mesh
    mesh0_mesh_29: THREE.Mesh
    mesh0_mesh_30: THREE.Mesh
    mesh0_mesh_31: THREE.Mesh
    mesh0_mesh_32: THREE.Mesh
    mesh0_mesh_33: THREE.Mesh
    mesh0_mesh_34: THREE.Mesh
    mesh0_mesh_35: THREE.Mesh
    mesh0_mesh_36: THREE.Mesh
    mesh0_mesh_37: THREE.Mesh
    mesh0_mesh_38: THREE.Mesh
    mesh0_mesh_39: THREE.Mesh
    mesh134_mesh: THREE.Mesh
    mesh134_mesh_1: THREE.Mesh
    mesh134_mesh_2: THREE.Mesh
    mesh134_mesh_3: THREE.Mesh
    mesh134_mesh_4: THREE.Mesh
    mesh134_mesh_5: THREE.Mesh
    mesh134_mesh_6: THREE.Mesh
    mesh134_mesh_7: THREE.Mesh
    mesh134_mesh_8: THREE.Mesh
    mesh134_mesh_9: THREE.Mesh
    mesh134_mesh_10: THREE.Mesh
    mesh134_mesh_11: THREE.Mesh
    mesh134_mesh_12: THREE.Mesh
    mesh134_mesh_13: THREE.Mesh
    mesh134_mesh_14: THREE.Mesh
    mesh134_mesh_15: THREE.Mesh
    mesh134_mesh_16: THREE.Mesh
    mesh134_mesh_17: THREE.Mesh
    mesh152_mesh: THREE.Mesh
    mesh152_mesh_1: THREE.Mesh
    mesh152_mesh_2: THREE.Mesh
    mesh152_mesh_3: THREE.Mesh
    mesh152_mesh_4: THREE.Mesh
    mesh152_mesh_5: THREE.Mesh
    mesh152_mesh_6: THREE.Mesh
    mesh152_mesh_7: THREE.Mesh
    mesh152_mesh_8: THREE.Mesh
    mesh152_mesh_9: THREE.Mesh
    mesh152_mesh_10: THREE.Mesh
    mesh152_mesh_11: THREE.Mesh
    mesh152_mesh_12: THREE.Mesh
    mesh152_mesh_13: THREE.Mesh
    mesh152_mesh_14: THREE.Mesh
    mesh152_mesh_15: THREE.Mesh
    mesh152_mesh_16: THREE.Mesh
    mesh169_mesh: THREE.Mesh
    mesh169_mesh_1: THREE.Mesh
    mesh169_mesh_2: THREE.Mesh
    mesh169_mesh_3: THREE.Mesh
    mesh169_mesh_4: THREE.Mesh
    mesh169_mesh_5: THREE.Mesh
    mesh169_mesh_6: THREE.Mesh
    mesh169_mesh_7: THREE.Mesh
    mesh169_mesh_8: THREE.Mesh
    mesh169_mesh_9: THREE.Mesh
    mesh169_mesh_10: THREE.Mesh
    mesh169_mesh_11: THREE.Mesh
    mesh169_mesh_12: THREE.Mesh
    mesh169_mesh_13: THREE.Mesh
    mesh169_mesh_14: THREE.Mesh
    mesh169_mesh_15: THREE.Mesh
    mesh169_mesh_16: THREE.Mesh
    mesh169_mesh_17: THREE.Mesh
    mesh187_mesh: THREE.Mesh
    mesh187_mesh_1: THREE.Mesh
    mesh187_mesh_2: THREE.Mesh
    mesh187_mesh_3: THREE.Mesh
    mesh187_mesh_4: THREE.Mesh
    mesh187_mesh_5: THREE.Mesh
    mesh187_mesh_6: THREE.Mesh
    mesh187_mesh_7: THREE.Mesh
    mesh187_mesh_8: THREE.Mesh
    mesh187_mesh_9: THREE.Mesh
    mesh187_mesh_10: THREE.Mesh
    mesh187_mesh_11: THREE.Mesh
    mesh187_mesh_12: THREE.Mesh
    mesh187_mesh_13: THREE.Mesh
    mesh187_mesh_14: THREE.Mesh
    mesh187_mesh_15: THREE.Mesh
    mesh203_mesh: THREE.Mesh
    mesh203_mesh_1: THREE.Mesh
    mesh203_mesh_2: THREE.Mesh
    mesh203_mesh_3: THREE.Mesh
    mesh203_mesh_4: THREE.Mesh
    mesh203_mesh_5: THREE.Mesh
    mesh203_mesh_6: THREE.Mesh
    mesh203_mesh_7: THREE.Mesh
    mesh203_mesh_8: THREE.Mesh
    mesh203_mesh_9: THREE.Mesh
    mesh203_mesh_10: THREE.Mesh
    mesh203_mesh_11: THREE.Mesh
    mesh203_mesh_12: THREE.Mesh
    mesh203_mesh_13: THREE.Mesh
    mesh217_mesh: THREE.Mesh
    mesh217_mesh_1: THREE.Mesh
    mesh217_mesh_2: THREE.Mesh
    mesh217_mesh_3: THREE.Mesh
    mesh217_mesh_4: THREE.Mesh
    mesh217_mesh_5: THREE.Mesh
    Cable_Carrier_Spacer_Block: THREE.Mesh
  }
  materials: {
    PaletteMaterial001: THREE.MeshStandardMaterial
  }
}

// @ts-expect-error
export function Model(props: JSX.IntrinsicElements['group']) {
  // @ts-expect-error
  const { nodes, materials } = useGLTF('/cross_slide.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh
        name="Cable_Carrier_Spacer_Block"
        castShadow
        receiveShadow
        geometry={nodes.Cable_Carrier_Spacer_Block.geometry}
        material={materials.PaletteMaterial001}
        position={[0.03, 0.005, 0.061]}
        rotation={[-Math.PI / 2, 0, Math.PI]}
      />
      <mesh
        name="mesh0_mesh"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_1"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_1.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_2"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_2.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_3"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_3.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_4"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_4.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_5"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_5.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_6"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_6.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_7"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_7.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_8"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_8.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_9"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_9.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_10"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_10.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_11"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_11.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_12"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_12.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_13"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_13.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_14"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_14.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_15"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_15.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_16"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_16.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_17"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_17.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_18"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_18.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_19"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_19.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_20"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_20.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_21"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_21.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_22"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_22.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_23"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_23.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_24"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_24.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_25"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_25.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_26"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_26.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_27"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_27.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_28"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_28.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_29"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_29.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_30"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_30.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_31"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_31.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_32"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_32.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_33"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_33.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_34"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_34.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_35"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_35.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_36"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_36.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_37"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_37.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_38"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_38.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh0_mesh_39"
        castShadow
        receiveShadow
        geometry={nodes.mesh0_mesh_39.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh134_mesh"
        castShadow
        receiveShadow
        geometry={nodes.mesh134_mesh.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh134_mesh_1"
        castShadow
        receiveShadow
        geometry={nodes.mesh134_mesh_1.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh134_mesh_2"
        castShadow
        receiveShadow
        geometry={nodes.mesh134_mesh_2.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh134_mesh_3"
        castShadow
        receiveShadow
        geometry={nodes.mesh134_mesh_3.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh134_mesh_4"
        castShadow
        receiveShadow
        geometry={nodes.mesh134_mesh_4.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh134_mesh_5"
        castShadow
        receiveShadow
        geometry={nodes.mesh134_mesh_5.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh134_mesh_6"
        castShadow
        receiveShadow
        geometry={nodes.mesh134_mesh_6.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh134_mesh_7"
        castShadow
        receiveShadow
        geometry={nodes.mesh134_mesh_7.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh134_mesh_8"
        castShadow
        receiveShadow
        geometry={nodes.mesh134_mesh_8.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh134_mesh_9"
        castShadow
        receiveShadow
        geometry={nodes.mesh134_mesh_9.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh134_mesh_10"
        castShadow
        receiveShadow
        geometry={nodes.mesh134_mesh_10.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh134_mesh_11"
        castShadow
        receiveShadow
        geometry={nodes.mesh134_mesh_11.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh134_mesh_12"
        castShadow
        receiveShadow
        geometry={nodes.mesh134_mesh_12.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh134_mesh_13"
        castShadow
        receiveShadow
        geometry={nodes.mesh134_mesh_13.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh134_mesh_14"
        castShadow
        receiveShadow
        geometry={nodes.mesh134_mesh_14.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh134_mesh_15"
        castShadow
        receiveShadow
        geometry={nodes.mesh134_mesh_15.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh134_mesh_16"
        castShadow
        receiveShadow
        geometry={nodes.mesh134_mesh_16.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh134_mesh_17"
        castShadow
        receiveShadow
        geometry={nodes.mesh134_mesh_17.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh152_mesh"
        castShadow
        receiveShadow
        geometry={nodes.mesh152_mesh.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh152_mesh_1"
        castShadow
        receiveShadow
        geometry={nodes.mesh152_mesh_1.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh152_mesh_2"
        castShadow
        receiveShadow
        geometry={nodes.mesh152_mesh_2.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh152_mesh_3"
        castShadow
        receiveShadow
        geometry={nodes.mesh152_mesh_3.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh152_mesh_4"
        castShadow
        receiveShadow
        geometry={nodes.mesh152_mesh_4.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh152_mesh_5"
        castShadow
        receiveShadow
        geometry={nodes.mesh152_mesh_5.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh152_mesh_6"
        castShadow
        receiveShadow
        geometry={nodes.mesh152_mesh_6.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh152_mesh_7"
        castShadow
        receiveShadow
        geometry={nodes.mesh152_mesh_7.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh152_mesh_8"
        castShadow
        receiveShadow
        geometry={nodes.mesh152_mesh_8.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh152_mesh_9"
        castShadow
        receiveShadow
        geometry={nodes.mesh152_mesh_9.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh152_mesh_10"
        castShadow
        receiveShadow
        geometry={nodes.mesh152_mesh_10.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh152_mesh_11"
        castShadow
        receiveShadow
        geometry={nodes.mesh152_mesh_11.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh152_mesh_12"
        castShadow
        receiveShadow
        geometry={nodes.mesh152_mesh_12.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh152_mesh_13"
        castShadow
        receiveShadow
        geometry={nodes.mesh152_mesh_13.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh152_mesh_14"
        castShadow
        receiveShadow
        geometry={nodes.mesh152_mesh_14.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh152_mesh_15"
        castShadow
        receiveShadow
        geometry={nodes.mesh152_mesh_15.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh152_mesh_16"
        castShadow
        receiveShadow
        geometry={nodes.mesh152_mesh_16.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh169_mesh"
        castShadow
        receiveShadow
        geometry={nodes.mesh169_mesh.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh169_mesh_1"
        castShadow
        receiveShadow
        geometry={nodes.mesh169_mesh_1.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh169_mesh_2"
        castShadow
        receiveShadow
        geometry={nodes.mesh169_mesh_2.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh169_mesh_3"
        castShadow
        receiveShadow
        geometry={nodes.mesh169_mesh_3.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh169_mesh_4"
        castShadow
        receiveShadow
        geometry={nodes.mesh169_mesh_4.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh169_mesh_5"
        castShadow
        receiveShadow
        geometry={nodes.mesh169_mesh_5.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh169_mesh_6"
        castShadow
        receiveShadow
        geometry={nodes.mesh169_mesh_6.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh169_mesh_7"
        castShadow
        receiveShadow
        geometry={nodes.mesh169_mesh_7.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh169_mesh_8"
        castShadow
        receiveShadow
        geometry={nodes.mesh169_mesh_8.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh169_mesh_9"
        castShadow
        receiveShadow
        geometry={nodes.mesh169_mesh_9.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh169_mesh_10"
        castShadow
        receiveShadow
        geometry={nodes.mesh169_mesh_10.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh169_mesh_11"
        castShadow
        receiveShadow
        geometry={nodes.mesh169_mesh_11.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh169_mesh_12"
        castShadow
        receiveShadow
        geometry={nodes.mesh169_mesh_12.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh169_mesh_13"
        castShadow
        receiveShadow
        geometry={nodes.mesh169_mesh_13.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh169_mesh_14"
        castShadow
        receiveShadow
        geometry={nodes.mesh169_mesh_14.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh169_mesh_15"
        castShadow
        receiveShadow
        geometry={nodes.mesh169_mesh_15.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh169_mesh_16"
        castShadow
        receiveShadow
        geometry={nodes.mesh169_mesh_16.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh169_mesh_17"
        castShadow
        receiveShadow
        geometry={nodes.mesh169_mesh_17.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh187_mesh"
        castShadow
        receiveShadow
        geometry={nodes.mesh187_mesh.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh187_mesh_1"
        castShadow
        receiveShadow
        geometry={nodes.mesh187_mesh_1.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh187_mesh_2"
        castShadow
        receiveShadow
        geometry={nodes.mesh187_mesh_2.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh187_mesh_3"
        castShadow
        receiveShadow
        geometry={nodes.mesh187_mesh_3.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh187_mesh_4"
        castShadow
        receiveShadow
        geometry={nodes.mesh187_mesh_4.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh187_mesh_5"
        castShadow
        receiveShadow
        geometry={nodes.mesh187_mesh_5.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh187_mesh_6"
        castShadow
        receiveShadow
        geometry={nodes.mesh187_mesh_6.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh187_mesh_7"
        castShadow
        receiveShadow
        geometry={nodes.mesh187_mesh_7.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh187_mesh_8"
        castShadow
        receiveShadow
        geometry={nodes.mesh187_mesh_8.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh187_mesh_9"
        castShadow
        receiveShadow
        geometry={nodes.mesh187_mesh_9.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh187_mesh_10"
        castShadow
        receiveShadow
        geometry={nodes.mesh187_mesh_10.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh187_mesh_11"
        castShadow
        receiveShadow
        geometry={nodes.mesh187_mesh_11.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh187_mesh_12"
        castShadow
        receiveShadow
        geometry={nodes.mesh187_mesh_12.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh187_mesh_13"
        castShadow
        receiveShadow
        geometry={nodes.mesh187_mesh_13.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh187_mesh_14"
        castShadow
        receiveShadow
        geometry={nodes.mesh187_mesh_14.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh187_mesh_15"
        castShadow
        receiveShadow
        geometry={nodes.mesh187_mesh_15.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh203_mesh"
        castShadow
        receiveShadow
        geometry={nodes.mesh203_mesh.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh203_mesh_1"
        castShadow
        receiveShadow
        geometry={nodes.mesh203_mesh_1.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh203_mesh_2"
        castShadow
        receiveShadow
        geometry={nodes.mesh203_mesh_2.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh203_mesh_3"
        castShadow
        receiveShadow
        geometry={nodes.mesh203_mesh_3.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh203_mesh_4"
        castShadow
        receiveShadow
        geometry={nodes.mesh203_mesh_4.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh203_mesh_5"
        castShadow
        receiveShadow
        geometry={nodes.mesh203_mesh_5.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh203_mesh_6"
        castShadow
        receiveShadow
        geometry={nodes.mesh203_mesh_6.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh203_mesh_7"
        castShadow
        receiveShadow
        geometry={nodes.mesh203_mesh_7.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh203_mesh_8"
        castShadow
        receiveShadow
        geometry={nodes.mesh203_mesh_8.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh203_mesh_9"
        castShadow
        receiveShadow
        geometry={nodes.mesh203_mesh_9.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh203_mesh_10"
        castShadow
        receiveShadow
        geometry={nodes.mesh203_mesh_10.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh203_mesh_11"
        castShadow
        receiveShadow
        geometry={nodes.mesh203_mesh_11.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh203_mesh_12"
        castShadow
        receiveShadow
        geometry={nodes.mesh203_mesh_12.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh203_mesh_13"
        castShadow
        receiveShadow
        geometry={nodes.mesh203_mesh_13.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh217_mesh"
        castShadow
        receiveShadow
        geometry={nodes.mesh217_mesh.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh217_mesh_1"
        castShadow
        receiveShadow
        geometry={nodes.mesh217_mesh_1.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh217_mesh_2"
        castShadow
        receiveShadow
        geometry={nodes.mesh217_mesh_2.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh217_mesh_3"
        castShadow
        receiveShadow
        geometry={nodes.mesh217_mesh_3.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh217_mesh_4"
        castShadow
        receiveShadow
        geometry={nodes.mesh217_mesh_4.geometry}
        material={materials.PaletteMaterial001}
      />
      <mesh
        name="mesh217_mesh_5"
        castShadow
        receiveShadow
        geometry={nodes.mesh217_mesh_5.geometry}
        material={materials.PaletteMaterial001}
      />
    </group>
  )
}

useGLTF.preload('/cross_slide.glb')
