/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { SCENE_MODEL_URL } from "../Constants.ts";

export default function Model(props: any) {
  const { nodes, materials } = useGLTF(SCENE_MODEL_URL);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube004.geometry}
        material={materials["Material.001"]}
        position={[7.679, -5.593, 26.377]}
        scale={0.5}
      />
    </group>
  );
}

useGLTF.preload(SCENE_MODEL_URL);
