# import { gql, useQuery } from '@apollo/client'

# const GetCharacters = gql`
query GetCharacters ($first: Int, $last: Int, $after: String, $before: String) {
  characters (first: $first, last: $last, after: $after, before: $before) {
    nodes {
      id
      characterId
      title
      content
      status
      link
      modified
      # CUSTOM FIELDS
      # owner # == user
      version
      # state
      # userType
      # RELATIONSHIPS
      threed
      name_full
      name_first
      name_last
      website
      occupation
    }
  }
}
# `
