# import { gql, useQuery } from '@apollo/client'

# const GetCharacters = gql`
query GetCharacters ($first: Int, $last: Int, $after: String, $before: String) {
  characters (first: $first, last: $last, after: $after, before: $before) {
    nodes {
      id
      characterId
      title
      content
      status
      link
      modified
      # CUSTOM FIELDS
      # owner # == user
      version
      # state
      nameFull
      nameFirst
      nameLast
      website
      occupation
      # RELATIONSHIPS
      threed {
        nodes {
          id
          title
          modelFiles {
            nodes {
              id
              title
              url
            }
          }
        }
      }
    }
  }
}
# `
