# import { gql, useQuery } from '@apollo/client'

# const GetFiles = gql`
query GetFiles ($first: Int, $last: Int, $after: String, $before: String) {
  files (first: $first, last: $last, after: $after, before: $before) {
    nodes {
      id
      fileId
      title
      content
      status
      link
      modified
      # custom fields
      # owner # == user
      version
      # state
      # userType
    }
  }
}
# `
