# import { gql, useQuery } from '@apollo/client'

# const GetFarmBots = gql`
query GetFarmBots ($first: Int, $last: Int, $after: String, $before: String) {
  farmbots (first: $first, last: $last, after: $after, before: $before) {
    nodes {
      id
      farmbotId
      title
      content
      status
      link
      modified
      # custom fields
      # owner # == user
      version
      # state
      # userType
      # character
      # userName
      # userPassword
      # nameFull
      # nameFirst
      # nameLast
      # email
      # phone
      # website
      # githubUserName
      # githubRepository
    }
  }
}
# `
