# import { gql, useQuery } from '@apollo/client'

# const GetParticipants = gql`
query GetParticipants ($first: Int, $last: Int, $after: String, $before: String) {
  participants (first: $first, last: $last, after: $after, before: $before) {
    nodes {
      id
      participantId
      title
      content
      status
      link
      modified
      # custom fields
      owner # == user
      version
      state
      userType
      ## participants
      character
      userName
      userPassword
      nameFull
      nameFirst
      nameLast
      email
      phone
      website
      githubUserName
      githubRepository
    }
  }
}
# `
