# import { gql, useQuery } from '@apollo/client'

# const GetPreferences = gql`
query GetPreferences ($first: Int, $last: Int, $after: String, $before: String) {
  preferencess (first: $first, last: $last, after: $after, before: $before) {
    nodes {
      id
      preferencesId
      title
      content
      status
      link
      modified
      # custom fields
      owner {
        node {
          userId
          userType
          username
          state
          version
        }
      }
      version
      doAutoLoadData
      doAutoRotate
      projectName
      environmentPreset
      environmentBgBlur
      characterTrailColor
      doCharacterAnimation
      doWorldDebug
      doWorldTesting
      doWorldPhysics
      doWorldControl
      doWorldUnfollowCam
      showPanelFirst
      showPanelLast
    }
  }
}
# `
