# import { gql, useQuery } from '@apollo/client'

# const GetPreferences = gql`
query GetPreferences ($first: Int, $last: Int, $after: String, $before: String) {
  preferencess (first: $first, last: $last, after: $after, before: $before) {
    nodes {
      preferencesId
      title
      content
      status
      link
      modified
      # custom fields
      version
      # owner
      doAutoLoadData
      doAutoRotate
      projectName
      environmentPreset
      environmentBgBlur
      doCharacterAnimation
      doWorldDebug
      doWorldTesting
      doWorldPhysics
      doWorldControl
      doWorldUnfollowCam
      showPanelFirst
      showPanelLast
    }
  }
}
# `
