# import { gql, useQuery } from '@apollo/client'

# const GetUsers = gql`
query GetUsers ($first: Int, $last: Int, $after: String, $before: String) {
  users (first: $first, last: $last, after: $after, before: $before) {
    nodes {
      userId
      title
      content
      status
      link
      modified
      # custom fields
      owner
      version
      state
      userType
      ## participants
      character
      userName
      userPassword
      nameFull
      nameFirst
      nameLast
      email
      phone
      website
      githubUserName
      githubRepository
    }
  }
}
# `
