# import { gql, useQuery } from '@apollo/client'

# const GetUsers = gql`
query GetUsers ($first: Int, $last: Int, $after: String, $before: String) {
  users (first: $first, last: $last, after: $after, before: $before) {
    nodes {
      id
      userId
      title
      content
      status
      link
      modified
    }
  }
}
# `
