# import { useMutation, gql } from '@apollo/client'

# const loginUser = gql`

# GraphQL Type: LoginUserInput!
mutation LoginUser ( 
    # $id: ID! # == clientMutationId
    $username: String! 
    $password: String!
){
  login(
    input: {
        # clientMutationId: $id
        username: $username
        password: $password
    }) {
    authToken
    refreshToken
    clientMutationId
    user {
      id
      name
    }
  }
}
# `
