/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Ddiaz Design (https://sketchfab.com/ddiaz-design)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/2002-mercedes-benz-e320-w210-4matic-sedan-5ddd3b440cf0496782948d765b8ef0c4
Title: 2002 Mercedes-Benz E320 W210 4Matic Sedan
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    mSM_Base_0000_001_SM_Base_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_0: THREE.Mesh
    mSM_Base_0000_001_SM_Base_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_mMAT_E320_W210_4matic_Sedan_2001_Black1_0: THREE.Mesh
    mSM_Base_0000_001_SM_Base_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey2_mMAT_Lights1_0: THREE.Mesh
    mSM_Base_0000_001_SM_Base_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey3_mMAT_Glass1_0: THREE.Mesh
    mSM_Base_0000_001_SM_Base_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey4_mMAT_Details_EXT1_0: THREE.Mesh
    mSM_Base_0000_001_SM_Base_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey5_mMAT_Details_MAT1_0: THREE.Mesh
    mSM_Brake_FL_0000_001_SM_Brake_FL_0000_001_MAT_Tire_Brake_mMAT_Tire_Brake1_0: THREE.Mesh
    mSM_Brake_FR_0000_001_SM_Brake_FR_0000_001_MAT_Tire_Brake_011_mMAT_Tire_Brake1_0: THREE.Mesh
    mSM_Brake_RL_0000_001_SM_Brake_RL_0000_001_MAT_Tire_Brake_022_mMAT_Tire_Brake1_0: THREE.Mesh
    mSM_Brake_RR_0000_001_SM_Brake_RR_0000_001_MAT_Tire_Brake_033_mMAT_Tire_Brake1_0: THREE.Mesh
    mSM_Disk_L_0000_001_SM_Disk_L_0000_001_MAT_Tire_Disk_mMAT_Tire_Disk1_0: THREE.Mesh
    mSM_Disk_R_0000_001_SM_Disk_R_0000_001_MAT_Tire_Disk_011_mMAT_Tire_Disk1_0: THREE.Mesh
    mSM_FrontKit_0000_001_SM_FrontKit_0000_001_MAT_Glass_004_mMAT_Glass1_0: THREE.Mesh
    mSM_FrontKit_0000_001_SM_FrontKit_0000_001_MAT_Glass_005_mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_0: THREE.Mesh
    mSM_FrontKit_0000_001_SM_FrontKit_0000_001_MAT_Glass_006_mMAT_Lights1_0: THREE.Mesh
    mSM_FrontKit_0000_001_SM_FrontKit_0000_001_MAT_Glass_007_mMAT_Details_MAT1_0: THREE.Mesh
    mSM_FrontKit_0000_001_SM_FrontKit_0000_001_MAT_Glass_008_mMAT_Details_Chassis_0000_006_0: THREE.Mesh
    mSM_FrontKit_0000_001_SM_FrontKit_0000_001_MAT_Glass_009_mMAT_Details_Grid_02_0: THREE.Mesh
    mSM_Hood_0000_001_SM_Hood_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_030_mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_0: THREE.Mesh
    mSM_Hood_0000_001_SM_Hood_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_031_mMAT_Details_EXT1_0: THREE.Mesh
    mSM_Hood_0000_001_SM_Hood_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_032_mMAT_Details_MAT1_0: THREE.Mesh
    mSM_Hub_L_0000_001_SM_Hub_L_0000_001_MAT_Tire_Hub_mMAT_Tire_Hub1_0: THREE.Mesh
    mSM_Hub_R_0000_001_SM_Hub_R_0000_001_MAT_Tire_Hub_009_mMAT_Tire_Hub_010_0: THREE.Mesh
    mSM_Interior_0000_001_SM_Interior_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_043_mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_0: THREE.Mesh
    mSM_Interior_0000_001_SM_Interior_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_044_mMAT_Lights1_0: THREE.Mesh
    mSM_Interior_0000_001_SM_Interior_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_045_mMAT_Details_MAT1_0: THREE.Mesh
    mSM_Interior_0000_001_SM_Interior_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_046_mMAT_Details_INT1_0: THREE.Mesh
    mSM_Interior_0000_001_SM_Interior_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_047_mMAT_Details_Add_02_0: THREE.Mesh
    mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_049_mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_0: THREE.Mesh
    mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_050_mMAT_E320_W210_4matic_Sedan_2001_Black1_0: THREE.Mesh
    mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_051_mMAT_Lights1_0: THREE.Mesh
    mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_052_mMAT_Glass1_0: THREE.Mesh
    mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_053_mMAT_Details_EXT1_0: THREE.Mesh
    mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_054_mMAT_Details_MAT1_0: THREE.Mesh
    mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_055_mMAT_Details_Chassis_0000_006_0: THREE.Mesh
    mSM_Root_E320_W210_4Matic_Sedan_2001_001_SM_Root_E320_W210_4Matic_Sedan_2001_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_05_mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_0: THREE.Mesh
    ['15_tire_map_c_tire1_0']: THREE.Mesh
    ['16_tire_map_c_tire1_0']: THREE.Mesh
    SM_Disk_R_0000_001_SM_Disk_R_0000_001_MAT_Tire_Disk_011_mMAT_Tire_Disk1_0: THREE.Mesh
    SM_Hub_R_0000_001_SM_Hub_R_0000_001_MAT_Tire_Hub_009_mMAT_Tire_Hub_010_0: THREE.Mesh
    SM_Disk_L_0000_001_SM_Disk_L_0000_001_MAT_Tire_Disk_mMAT_Tire_Disk1_0: THREE.Mesh
    SM_Hub_L_0000_001_SM_Hub_L_0000_001_MAT_Tire_Hub_mMAT_Tire_Hub1_0: THREE.Mesh
  }
  materials: {
    mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1: THREE.MeshPhysicalMaterial
    mMAT_E320_W210_4matic_Sedan_2001_Black1: THREE.MeshPhysicalMaterial
    mMAT_Lights1: THREE.MeshPhysicalMaterial
    mMAT_Glass1: THREE.MeshPhysicalMaterial
    mMAT_Details_EXT1: THREE.MeshPhysicalMaterial
    mMAT_Details_MAT1: THREE.MeshPhysicalMaterial
    mMAT_Tire_Brake1: THREE.MeshPhysicalMaterial
    mMAT_Tire_Disk1: THREE.MeshStandardMaterial
    mMAT_Details_Chassis_0000_006: THREE.MeshPhysicalMaterial
    mMAT_Details_Grid_02: THREE.MeshPhysicalMaterial
    mMAT_Tire_Hub1: THREE.MeshPhysicalMaterial
    mMAT_Tire_Hub_010: THREE.MeshPhysicalMaterial
    mMAT_Details_INT1: THREE.MeshPhysicalMaterial
    mMAT_Details_Add_02: THREE.MeshPhysicalMaterial
    tire1: THREE.MeshPhysicalMaterial
  }
}

// @ts-expect-error
export function Model(props: JSX.IntrinsicElements['group']) {
  // @ts-expect-error
  const { nodes, materials } = useGLTF(
    '/assets/mercedes/2002_mercedes-benz_e320_w210_4matic_sedan.glb'
  ) as GLTFResult
    <group {...props} dispose={null}>
      <group name="FINAL_MODEL_02fbx" scale={0.01}>
        <mesh
          name="mSM_Base_0000_001_SM_Base_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_Base_0000_001_SM_Base_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_0
              .geometry
          }
          material={materials.mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_Base_0000_001_SM_Base_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_mMAT_E320_W210_4matic_Sedan_2001_Black1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_Base_0000_001_SM_Base_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_mMAT_E320_W210_4matic_Sedan_2001_Black1_0
              .geometry
          }
          material={materials.mMAT_E320_W210_4matic_Sedan_2001_Black1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_Base_0000_001_SM_Base_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey2_mMAT_Lights1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_Base_0000_001_SM_Base_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey2_mMAT_Lights1_0
              .geometry
          }
          material={materials.mMAT_Lights1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_Base_0000_001_SM_Base_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey3_mMAT_Glass1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_Base_0000_001_SM_Base_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey3_mMAT_Glass1_0
              .geometry
          }
          material={materials.mMAT_Glass1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_Base_0000_001_SM_Base_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey4_mMAT_Details_EXT1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_Base_0000_001_SM_Base_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey4_mMAT_Details_EXT1_0
              .geometry
          }
          material={materials.mMAT_Details_EXT1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_Base_0000_001_SM_Base_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey5_mMAT_Details_MAT1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_Base_0000_001_SM_Base_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey5_mMAT_Details_MAT1_0
              .geometry
          }
          material={materials.mMAT_Details_MAT1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_Brake_FL_0000_001_SM_Brake_FL_0000_001_MAT_Tire_Brake_mMAT_Tire_Brake1_0"
          castShadow
          receiveShadow
          geometry={
            nodes.mSM_Brake_FL_0000_001_SM_Brake_FL_0000_001_MAT_Tire_Brake_mMAT_Tire_Brake1_0
              .geometry
          }
          material={materials.mMAT_Tire_Brake1}
          position={[0.687, 0.326, 1.434]}
          scale={[1, 0.917, 0.917]}
        />
        <mesh
          name="mSM_Brake_FR_0000_001_SM_Brake_FR_0000_001_MAT_Tire_Brake_011_mMAT_Tire_Brake1_0"
          castShadow
          receiveShadow
          geometry={
            nodes.mSM_Brake_FR_0000_001_SM_Brake_FR_0000_001_MAT_Tire_Brake_011_mMAT_Tire_Brake1_0
              .geometry
          }
          material={materials.mMAT_Tire_Brake1}
          position={[-0.687, 0.326, 1.434]}
          scale={[1, 0.917, 0.917]}
        />
        <mesh
          name="mSM_Brake_RL_0000_001_SM_Brake_RL_0000_001_MAT_Tire_Brake_022_mMAT_Tire_Brake1_0"
          castShadow
          receiveShadow
          geometry={
            nodes.mSM_Brake_RL_0000_001_SM_Brake_RL_0000_001_MAT_Tire_Brake_022_mMAT_Tire_Brake1_0
              .geometry
          }
          material={materials.mMAT_Tire_Brake1}
          position={[0.687, 0.326, -1.389]}
          scale={[1.011, 0.927, 0.927]}
        />
        <mesh
          name="mSM_Brake_RR_0000_001_SM_Brake_RR_0000_001_MAT_Tire_Brake_033_mMAT_Tire_Brake1_0"
          castShadow
          receiveShadow
          geometry={
            nodes.mSM_Brake_RR_0000_001_SM_Brake_RR_0000_001_MAT_Tire_Brake_033_mMAT_Tire_Brake1_0
              .geometry
          }
          material={materials.mMAT_Tire_Brake1}
          position={[-0.687, 0.326, -1.389]}
          scale={[1.011, 0.927, 0.927]}
        />
        <mesh
          name="mSM_Disk_L_0000_001_SM_Disk_L_0000_001_MAT_Tire_Disk_mMAT_Tire_Disk1_0"
          castShadow
          receiveShadow
          geometry={
            nodes.mSM_Disk_L_0000_001_SM_Disk_L_0000_001_MAT_Tire_Disk_mMAT_Tire_Disk1_0.geometry
          }
          material={materials.mMAT_Tire_Disk1}
          position={[0.687, 0.326, 1.434]}
          scale={[1, 0.917, 0.917]}
        />
        <mesh
          name="mSM_Disk_R_0000_001_SM_Disk_R_0000_001_MAT_Tire_Disk_011_mMAT_Tire_Disk1_0"
          castShadow
          receiveShadow
          geometry={
            nodes.mSM_Disk_R_0000_001_SM_Disk_R_0000_001_MAT_Tire_Disk_011_mMAT_Tire_Disk1_0
              .geometry
          }
          material={materials.mMAT_Tire_Disk1}
          position={[-0.687, 0.326, 1.434]}
          scale={[1, 0.917, 0.917]}
        />
        <mesh
          name="mSM_FrontKit_0000_001_SM_FrontKit_0000_001_MAT_Glass_004_mMAT_Glass1_0"
          castShadow
          receiveShadow
          geometry={
            nodes.mSM_FrontKit_0000_001_SM_FrontKit_0000_001_MAT_Glass_004_mMAT_Glass1_0.geometry
          }
          material={materials.mMAT_Glass1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_FrontKit_0000_001_SM_FrontKit_0000_001_MAT_Glass_005_mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_FrontKit_0000_001_SM_FrontKit_0000_001_MAT_Glass_005_mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_0
              .geometry
          }
          material={materials.mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_FrontKit_0000_001_SM_FrontKit_0000_001_MAT_Glass_006_mMAT_Lights1_0"
          castShadow
          receiveShadow
          geometry={
            nodes.mSM_FrontKit_0000_001_SM_FrontKit_0000_001_MAT_Glass_006_mMAT_Lights1_0.geometry
          }
          material={materials.mMAT_Lights1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_FrontKit_0000_001_SM_FrontKit_0000_001_MAT_Glass_007_mMAT_Details_MAT1_0"
          castShadow
          receiveShadow
          geometry={
            nodes.mSM_FrontKit_0000_001_SM_FrontKit_0000_001_MAT_Glass_007_mMAT_Details_MAT1_0
              .geometry
          }
          material={materials.mMAT_Details_MAT1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_FrontKit_0000_001_SM_FrontKit_0000_001_MAT_Glass_008_mMAT_Details_Chassis_0000_006_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_FrontKit_0000_001_SM_FrontKit_0000_001_MAT_Glass_008_mMAT_Details_Chassis_0000_006_0
              .geometry
          }
          material={materials.mMAT_Details_Chassis_0000_006}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_FrontKit_0000_001_SM_FrontKit_0000_001_MAT_Glass_009_mMAT_Details_Grid_02_0"
          castShadow
          receiveShadow
          geometry={
            nodes.mSM_FrontKit_0000_001_SM_FrontKit_0000_001_MAT_Glass_009_mMAT_Details_Grid_02_0
              .geometry
          }
          material={materials.mMAT_Details_Grid_02}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_Hood_0000_001_SM_Hood_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_030_mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_Hood_0000_001_SM_Hood_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_030_mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_0
              .geometry
          }
          material={materials.mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_Hood_0000_001_SM_Hood_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_031_mMAT_Details_EXT1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_Hood_0000_001_SM_Hood_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_031_mMAT_Details_EXT1_0
              .geometry
          }
          material={materials.mMAT_Details_EXT1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_Hood_0000_001_SM_Hood_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_032_mMAT_Details_MAT1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_Hood_0000_001_SM_Hood_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_032_mMAT_Details_MAT1_0
              .geometry
          }
          material={materials.mMAT_Details_MAT1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_Hub_L_0000_001_SM_Hub_L_0000_001_MAT_Tire_Hub_mMAT_Tire_Hub1_0"
          castShadow
          receiveShadow
          geometry={
            nodes.mSM_Hub_L_0000_001_SM_Hub_L_0000_001_MAT_Tire_Hub_mMAT_Tire_Hub1_0.geometry
          }
          material={materials.mMAT_Tire_Hub1}
          position={[0.687, 0.326, 1.434]}
          scale={[1, 0.917, 0.917]}
        />
        <mesh
          name="mSM_Hub_R_0000_001_SM_Hub_R_0000_001_MAT_Tire_Hub_009_mMAT_Tire_Hub_010_0"
          castShadow
          receiveShadow
          geometry={
            nodes.mSM_Hub_R_0000_001_SM_Hub_R_0000_001_MAT_Tire_Hub_009_mMAT_Tire_Hub_010_0.geometry
          }
          material={materials.mMAT_Tire_Hub_010}
          position={[-0.687, 0.326, 1.434]}
          scale={[1, 0.917, 0.917]}
        />
        <mesh
          name="mSM_Interior_0000_001_SM_Interior_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_043_mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_Interior_0000_001_SM_Interior_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_043_mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_0
              .geometry
          }
          material={materials.mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_Interior_0000_001_SM_Interior_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_044_mMAT_Lights1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_Interior_0000_001_SM_Interior_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_044_mMAT_Lights1_0
              .geometry
          }
          material={materials.mMAT_Lights1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_Interior_0000_001_SM_Interior_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_045_mMAT_Details_MAT1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_Interior_0000_001_SM_Interior_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_045_mMAT_Details_MAT1_0
              .geometry
          }
          material={materials.mMAT_Details_MAT1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_Interior_0000_001_SM_Interior_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_046_mMAT_Details_INT1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_Interior_0000_001_SM_Interior_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_046_mMAT_Details_INT1_0
              .geometry
          }
          material={materials.mMAT_Details_INT1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_Interior_0000_001_SM_Interior_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_047_mMAT_Details_Add_02_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_Interior_0000_001_SM_Interior_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_047_mMAT_Details_Add_02_0
              .geometry
          }
          material={materials.mMAT_Details_Add_02}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_049_mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_049_mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_0
              .geometry
          }
          material={materials.mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_050_mMAT_E320_W210_4matic_Sedan_2001_Black1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_050_mMAT_E320_W210_4matic_Sedan_2001_Black1_0
              .geometry
          }
          material={materials.mMAT_E320_W210_4matic_Sedan_2001_Black1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_051_mMAT_Lights1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_051_mMAT_Lights1_0
              .geometry
          }
          material={materials.mMAT_Lights1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_052_mMAT_Glass1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_052_mMAT_Glass1_0
              .geometry
          }
          material={materials.mMAT_Glass1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_053_mMAT_Details_EXT1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_053_mMAT_Details_EXT1_0
              .geometry
          }
          material={materials.mMAT_Details_EXT1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_054_mMAT_Details_MAT1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_054_mMAT_Details_MAT1_0
              .geometry
          }
          material={materials.mMAT_Details_MAT1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_055_mMAT_Details_Chassis_0000_006_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_RearKit_0000_001_SM_RearKit_0000_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_055_mMAT_Details_Chassis_0000_006_0
              .geometry
          }
          material={materials.mMAT_Details_Chassis_0000_006}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="mSM_Root_E320_W210_4Matic_Sedan_2001_001_SM_Root_E320_W210_4Matic_Sedan_2001_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_05_mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_0"
          castShadow
          receiveShadow
          geometry={
            nodes
              .mSM_Root_E320_W210_4Matic_Sedan_2001_001_SM_Root_E320_W210_4Matic_Sedan_2001_001_MAT_E320_W210_4matic_Sedan_2001_Metallic_Grey_05_mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1_0
              .geometry
          }
          material={materials.mMAT_E320_W210_4matic_Sedan_2001_Metallic_Grey1}
          position={[0, 0.192, 0.021]}
          rotation={[0.005, 0, 0]}
        />
        <mesh
          name="15_tire_map_c_tire1_0"
          castShadow
          receiveShadow
          geometry={nodes['15_tire_map_c_tire1_0'].geometry}
          material={materials.tire1}
          position={[0, 0, 0.003]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.01}
        />
        <mesh
          name="16_tire_map_c_tire1_0"
          castShadow
          receiveShadow
          geometry={nodes['16_tire_map_c_tire1_0'].geometry}
          material={materials.tire1}
          position={[0, 0, -0.124]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.01}
        />
        <mesh
          name="SM_Disk_R_0000_001_SM_Disk_R_0000_001_MAT_Tire_Disk_011_mMAT_Tire_Disk1_0"
          castShadow
          receiveShadow
          geometry={
            nodes.SM_Disk_R_0000_001_SM_Disk_R_0000_001_MAT_Tire_Disk_011_mMAT_Tire_Disk1_0.geometry
          }
          material={materials.mMAT_Tire_Disk1}
          position={[-0.687, 0.326, -1.389]}
          scale={[1.011, 0.927, 0.927]}
        />
        <mesh
          name="SM_Hub_R_0000_001_SM_Hub_R_0000_001_MAT_Tire_Hub_009_mMAT_Tire_Hub_010_0"
          castShadow
          receiveShadow
          geometry={
            nodes.SM_Hub_R_0000_001_SM_Hub_R_0000_001_MAT_Tire_Hub_009_mMAT_Tire_Hub_010_0.geometry
          }
          material={materials.mMAT_Tire_Hub_010}
          position={[-0.687, 0.326, -1.389]}
          scale={[1.011, 0.927, 0.927]}
        />
        <mesh
          name="SM_Disk_L_0000_001_SM_Disk_L_0000_001_MAT_Tire_Disk_mMAT_Tire_Disk1_0"
          castShadow
          receiveShadow
          geometry={
            nodes.SM_Disk_L_0000_001_SM_Disk_L_0000_001_MAT_Tire_Disk_mMAT_Tire_Disk1_0.geometry
          }
          material={materials.mMAT_Tire_Disk1}
          position={[0.687, 0.326, -1.389]}
          scale={[1.011, 0.927, 0.927]}
        />
        <mesh
          name="SM_Hub_L_0000_001_SM_Hub_L_0000_001_MAT_Tire_Hub_mMAT_Tire_Hub1_0"
          castShadow
          receiveShadow
          geometry={
            nodes.SM_Hub_L_0000_001_SM_Hub_L_0000_001_MAT_Tire_Hub_mMAT_Tire_Hub1_0.geometry
          }
          material={materials.mMAT_Tire_Hub1}
          position={[0.687, 0.326, -1.389]}
          scale={[1.011, 0.927, 0.927]}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/assets/mercedes/2002_mercedes-benz_e320_w210_4matic_sedan.glb')
